# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Build CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Translate Repo Name For Build Tools filename_prefix
      id: repo-name
      run: |
        echo "repo-name=$(
        echo ${{ github.repository }} |
        awk -F '\/' '{ print tolower($2) }' |
        tr '_' '-'
        )" >> $GITHUB_OUTPUT
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Versions
      run: |
        python3 --version
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Install deps
      run: |
        sudo apt update
        sudo apt-get install gettext otf2bdf xfonts-utils
        pip install -r requirements.txt
        pip install pre-commit
    - name: Library version
      run: git describe --dirty --always --tags
    - name: Pre-commit hooks
      run: |
        pre-commit run --all-files
    - name: Build assets
      run: python build.py
    - uses: actions/upload-artifact@v4
      with:
        path: dist
        name: bundle
    - name: Setup problem matchers
      uses: adafruit/circuitpython-action-library-ci-problem-matchers@v1
